name: Image Builder

on:
  label:
    types:
      - created
  push:
    branches:
      - master
  issues:
    types:
      - opened
      - labeled

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout copier
        uses: actions/checkout@master
        with:
          repository: phosae/ffmpegif
          path: ./ffmpegif

      - name: Short Commit ID
        id: commit
        run: |
          echo "COMMIT_ID=$(git --git-dir=./ffmpegif/.git --work-tree=./ffmpegif rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Show COMMIT_ID
        run: |
          echo "commit_id: ${{ env.COMMIT_ID }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: zengxu
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./ffmpegif
          # Note: tags has to be all lower-case
          tags: |
            zengxu/ffmpegif:latest,zengxu/ffmpegif:${{ env.COMMIT_ID }}
          platforms: |
            linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
